### ISSUE TITLE
[14.0][IMP]Contract Locations in WebSite Portal

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/contract#1]
Logged in as Costumer to Portal using

test@pmsaovicente.com.br

I Have this View

![image](https://user-images.githubusercontent.com/38361760/208921429-943522ff-9470-4578-8bc6-0c0f71c94ef0.png)

In the CONTRACT SECTION we should be able to make the administration of the contract.

Insert Locations
Insert Equipments to the list of Equipments

**Comment by rafnixg** [comment]
MD: initial issue:
You need to create a new module called, which creates a new item in the portal view for the "agreements"
